# Generated by Django 2.2.14 on 2022-01-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobsearch',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('jobname', models.CharField(max_length=200)),
                ('job', models.CharField(choices=[('engineer', 'Engineer'), ('testing', 'Testing'), ('manager', 'Manager')], default='engineer', max_length=25)),
                ('location', models.CharField(choices=[('chennai', 'Chennai'), ('bangalore', 'Bangalore'), ('hyderabad', 'Hyderabad')], default='chennai', max_length=25)),
                ('salary', models.CharField(choices=[('0-20k', '0-20k'), ('20-40k', '20-40k'), ('40-60k', '40-60k')], default='0-20k', max_length=25)),
                ('description', models.CharField(default='No description provided', max_length=1000)),
            ],
        ),
    ]
