# Generated by Django 2.2.14 on 2022-01-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplecheckboxapp', '0003_auto_20220120_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsearch',
            name='salary',
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='degree',
            field=models.CharField(choices=[('B.Arch', 'B.Arch'), ('B.com', 'B.com'), ('B.Pharm', 'B.Pharm')], default='B.Arch', max_length=25),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='job',
            field=models.CharField(choices=[('Accountant', 'Accountant'), ('BPO / Telecaller', 'BPO / Telecaller'), ('Customer Service / Tech Support', 'Customer Service / Tech Support')], default='Port Blair', max_length=25),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='location',
            field=models.CharField(choices=[('Port Blair', 'Port Blair'), ('Mayabunder', 'Mayabunder'), ('Nicobar', 'Nicobar')], default='Accountant', max_length=25),
        ),
    ]
