# Generated by Django 2.2.14 on 2022-01-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplecheckboxapp', '0005_auto_20220120_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearch',
            name='collegelocation',
            field=models.CharField(choices=[('Andaman &amp; Nicobar Islands', 'Andaman &amp; Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh')], default='Andaman &amp; Nicobar Islands', max_length=200),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='department',
            field=models.CharField(choices=[('Aeronautical / Avionics / Aerospace', 'Aeronautical / Avionics / Aerospace'), ('Agricultural / Irrigation', 'Agricultural / Irrigation'), ('Anesthesia (DA)', 'Anesthesia (DA)')], default='Aeronautical / Avionics / Aerospace', max_length=200),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Male', max_length=200),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='marks',
            field=models.CharField(choices=[('10th/12th/Degree - All Above 60%', '10th/12th/Degree - All Above 60%')], default='10th/12th/Degree - All Above 60%', max_length=200),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='passout',
            field=models.CharField(choices=[('2025', '2025'), ('2024', '2024'), ('2023', '2023')], default='2025', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='degree',
            field=models.CharField(choices=[('B.Arch', 'B.Arch'), ('B.com', 'B.com'), ('B.Pharm', 'B.Pharm'), ('BBA - BBM', 'BBA - BBM'), ('BCA', 'BCA'), ('BDS', 'BDS'), ('BE - BTech', 'BE - BTech'), ('BEd', 'BEd'), ('BHM', 'BHM'), ('BSc', 'BSc')], default='B.Arch', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='job',
            field=models.CharField(choices=[('Accountant', 'Accountant'), ('BPO / Telecaller', 'BPO / Telecaller'), ('Customer Service / Tech Support', 'Customer Service / Tech Support'), ('Engineer (Core, Non-IT)', 'Engineer (Core, Non-IT)'), ('Sales / Marketing Executive', 'Sales / Marketing Executive'), ('IT - Mobile Developer', 'T - Mobile Developer'), ('IT Software-Engineer', 'IT Software-Engineer'), ('Management Trainee', 'Management Trainee'), ('Mechanic / Fitter / Production', 'Mechanic / Fitter / Production'), ('Retail / Store Executive', 'Retail / Store Executive'), ('Architect', 'Architect'), ('Content Writer', 'Content Writer'), ('Data Entry /Back Office', 'Data Entry /Back Office'), ('Doctor / Physician', 'Doctor / Physician'), ('HR / Admin', 'HR / Admin'), ('IT Hardware Engineer', 'IT Hardware Engineer')], default='Port Blair', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='location',
            field=models.CharField(choices=[('Port Blair', 'Port Blair'), ('Mayabunder', 'Mayabunder'), ('Nicobar', 'Nicobar'), ('Andaman &amp; Nicobar Islands-other', 'Andaman &amp; Nicobar Islands-other'), ('East Godavari', 'East Godavari'), ('Eluru', 'Eluru'), ('Kadapa ', 'Kadapa '), (' Machilipatnam ', 'Machilipatnam '), (' Ongole ', ' Ongole '), (' Srikakulam ', ' Srikakulam '), (' Vijayawada ', ' Vijayawada '), (' Visakhapatnam ', ' Visakhapatnam '), (' Vizianagaram ', ' Vizianagaram '), ('Anantapur', 'Anantapur'), ('Guntakal', 'Guntakal'), ('Guntur', 'Guntur'), ('Kakinada', 'Kakinada'), ('Kurnool', 'Kurnool'), ('Nellore', 'Nellore'), ('Rajahmundry', 'Rajahmundry'), ('Tirupati', 'Tirupati'), ('Andhra Pradesh -Other', 'Andhra Pradesh -Other')], default='Accountant', max_length=200),
        ),
    ]
