# Generated by Django 2.2.14 on 2022-01-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplecheckboxapp', '0006_auto_20220120_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsearch',
            name='description',
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='passin',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default='2021', max_length=200),
        ),
    ]
